"""
LSTM Trainer for Crowd Stampede Detection
==========================================
This script reads the training_data.csv (generated by feature_extractor.py),
trains an LSTM neural network to identify panic/stampede sequences, and
saves the trained model weights as a .pth file.

Usage:
    python training/train_lstm.py --data training/data/training_data.csv --output backend/models/stampede_lstm.pth

Arguments:
    --data   : Path to the CSV file generated by feature_extractor.py
    --output : Where to save the trained model weights
    --epochs : How many training cycles to run (default: 30)
    --window : Number of consecutive frames per training sample (default: 30)
"""

import argparse
import os
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import json


# ─────────────────────────────────────────────
# Configuration
# ─────────────────────────────────────────────
FEATURES = ["crowd_count", "density_pct", "avg_speed", "direction_variance"]
LABEL_COL = "label"
WINDOW_SIZE = 30       # Number of consecutive frames per training sample
HIDDEN_SIZE = 64       # LSTM internal memory units
NUM_LAYERS = 2         # Stacked LSTM layers
BATCH_SIZE = 32
LEARNING_RATE = 0.001


# ─────────────────────────────────────────────
# Dataset: Sliding Window Generator
# ─────────────────────────────────────────────
class CrowdSequenceDataset(Dataset):
    """
    Converts a flat CSV into overlapping temporal windows.
    Each sample is WINDOW_SIZE consecutive rows (frames).
    The label is taken from the last row of the window.

    NOTE: Windows are pre-built so they can be shuffled and split
    without class-imbalance issues caused by ordered CSV data.
    """
    def __init__(self, windows, labels):
        self.windows = windows   # list of numpy arrays [window_size, features]
        self.labels  = labels    # list of float scalars

    def __len__(self):
        return len(self.windows)

    def __getitem__(self, idx):
        x_seq  = torch.tensor(self.windows[idx], dtype=torch.float32)
        y_label = torch.tensor(self.labels[idx],  dtype=torch.float32)
        return x_seq, y_label


def build_windows(X, y, window_size):
    """Build sliding windows from feature array X and label array y."""
    windows, labels = [], []
    for i in range(len(X) - window_size):
        windows.append(X[i: i + window_size])
        labels.append(float(y[i + window_size - 1]))
    return windows, labels


# ─────────────────────────────────────────────
# LSTM Model Definition
# ─────────────────────────────────────────────
class StampedeDetectorLSTM(nn.Module):
    def __init__(self, input_size, hidden_size, num_layers):
        super().__init__()
        self.lstm = nn.LSTM(
            input_size=input_size,
            hidden_size=hidden_size,
            num_layers=num_layers,
            batch_first=True,
            dropout=0.2
        )
        self.classifier = nn.Sequential(
            nn.Linear(hidden_size, 32),
            nn.ReLU(),
            nn.Linear(32, 1),
            nn.Sigmoid()   # Output: 0.0 (safe) to 1.0 (stampede probability)
        )

    def forward(self, x):
        # x shape: [batch, window_size, features]
        lstm_out, _ = self.lstm(x)
        # Use only the final time step's output
        last_step = lstm_out[:, -1, :]
        return self.classifier(last_step).squeeze(1)


# ─────────────────────────────────────────────
# Training Loop
# ─────────────────────────────────────────────
def train(data_path, output_path, epochs, window_size):
    print(f"\nLoading dataset: {data_path}")
    df = pd.read_csv(data_path)
    print(f"Total rows: {len(df)}")
    print(f"Label distribution:\n{df[LABEL_COL].value_counts().to_string()}")

    if len(df) < window_size + 10:
        print(f"ERROR: Dataset too small. Need at least {window_size + 10} rows.")
        return

    X = df[FEATURES].values
    y = df[LABEL_COL].values

    # Normalize features (critical for LSTM stability)
    scaler = StandardScaler()
    X = scaler.fit_transform(X)

    # Save scaler parameters so the live app can apply the same normalization
    scaler_path = output_path.replace(".pth", "_scaler.json")
    scaler_data = {
        "mean": scaler.mean_.tolist(),
        "scale": scaler.scale_.tolist(),
        "features": FEATURES
    }
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(scaler_path, "w") as f:
        json.dump(scaler_data, f, indent=2)
    print(f"Scaler saved: {scaler_path}")

    # Build all windows first, THEN shuffle + split
    # This ensures both classes are represented in train AND val
    all_windows, all_labels = build_windows(X, y, window_size)
    print(f"Total windows built: {len(all_windows)}")

    # Shuffle with fixed seed for reproducibility
    rng = np.random.default_rng(seed=42)
    indices = rng.permutation(len(all_windows))
    all_windows = [all_windows[i] for i in indices]
    all_labels  = [all_labels[i]  for i in indices]

    split = int(len(all_windows) * 0.8)
    train_windows, val_windows = all_windows[:split], all_windows[split:]
    train_labels,  val_labels  = all_labels[:split],  all_labels[split:]

    # Show class balance in each split
    train_pos = sum(train_labels)
    val_pos   = sum(val_labels)
    print(f"Train: {len(train_windows)} windows  ({int(train_pos)} unsafe / {len(train_windows)-int(train_pos)} safe)")
    print(f"Val:   {len(val_windows)} windows  ({int(val_pos)} unsafe / {len(val_windows)-int(val_pos)} safe)")

    train_ds = CrowdSequenceDataset(train_windows, train_labels)
    val_ds   = CrowdSequenceDataset(val_windows,   val_labels)

    train_dl = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True)
    val_dl   = DataLoader(val_ds,   batch_size=BATCH_SIZE, shuffle=False)

    # Select compute device (Apple Silicon MPS, CUDA GPU, or CPU)
    if torch.cuda.is_available():
        device = torch.device("cuda")
    elif torch.backends.mps.is_available():
        device = torch.device("mps")
    else:
        device = torch.device("cpu")
    print(f"Training device: {device}")

    model = StampedeDetectorLSTM(
        input_size=len(FEATURES),
        hidden_size=HIDDEN_SIZE,
        num_layers=NUM_LAYERS
    ).to(device)

    loss_fn = nn.BCELoss()
    optimizer = torch.optim.Adam(model.parameters(), lr=LEARNING_RATE)

    print(f"\nStarting training ({epochs} epochs, window={window_size} frames)...")
    print("-" * 50)

    best_val_loss = float("inf")

    for epoch in range(1, epochs + 1):
        # Training phase
        model.train()
        train_loss = 0.0
        for x_batch, y_batch in train_dl:
            x_batch, y_batch = x_batch.to(device), y_batch.to(device)
            optimizer.zero_grad()
            preds = model(x_batch)
            loss = loss_fn(preds, y_batch)
            loss.backward()
            optimizer.step()
            train_loss += loss.item()

        # Validation phase
        model.eval()
        val_loss = 0.0
        correct = 0
        total = 0
        with torch.no_grad():
            for x_batch, y_batch in val_dl:
                x_batch, y_batch = x_batch.to(device), y_batch.to(device)
                preds = model(x_batch)
                val_loss += loss_fn(preds, y_batch).item()
                predicted = (preds > 0.5).float()
                correct += (predicted == y_batch).sum().item()
                total += len(y_batch)

        avg_train = train_loss / max(len(train_dl), 1)
        avg_val   = val_loss   / max(len(val_dl), 1)
        accuracy  = (correct / total * 100) if total > 0 else 0.0

        print(f"Epoch {epoch:03d}/{epochs} | Train Loss: {avg_train:.4f} | Val Loss: {avg_val:.4f} | Val Accuracy: {accuracy:.1f}%")

        # Save checkpoint if best model so far
        if avg_val < best_val_loss:
            best_val_loss = avg_val
            torch.save(model.state_dict(), output_path)
            print(f"           ** New best model saved to {output_path} **")

    print("-" * 50)
    print(f"\nTraining complete.")
    print(f"Best model weights: {output_path}")
    print(f"Normalization data: {scaler_path}")
    print("\nNext step: Place both files in backend/models/ and update risk_analyzer.py to load them.")


# ─────────────────────────────────────────────
# Entry Point
# ─────────────────────────────────────────────
if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Train LSTM on extracted crowd features.")
    parser.add_argument("--data",   default="training/data/training_data.csv", help="Path to input CSV")
    parser.add_argument("--output", default="backend/models/stampede_lstm.pth", help="Path to save trained weights")
    parser.add_argument("--epochs", default=30, type=int, help="Number of training epochs")
    parser.add_argument("--window", default=30,  type=int, help="Sliding window size in frames")

    args = parser.parse_args()
    train(args.data, args.output, args.epochs, args.window)
